/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tubes;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.Transparency;
import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.net.URL;
import javafx.embed.swing.JFXPanel;
import static javafx.scene.input.DataFormat.URL;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.util.Duration;

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        aboutPanel.setVisible(false);
        helpPanel.setVisible(false);
        jFrame1.setVisible(false);
        jFrame2.setVisible(false);
        //saveScore.setVisible(false);
        highscoresPanel.setVisible(false);
        labelAbout.setBackground(new java.awt.Color(255, 255, 255, 50));
        helpLabel.setBackground(new java.awt.Color(255, 255, 255, 50));
        //saveScore.setBackground(new java.awt.Color(255, 255, 255, 50));
        highscoresPanel.setBackground(new java.awt.Color(255, 255, 255, 50));
        //System.out.println(this.getHeight());
        //System.out.println(this.getWidth());
        //tesFish1.setBackground(new java.awt.Color(255, 255, 255, 50));
        jFrame1.setDefaultCloseOperation(EXIT_ON_CLOSE);  
        jFrame2.setDefaultCloseOperation(EXIT_ON_CLOSE); 
        
        //jFrame1.setLocationRelativeTo(null);
        //jFrame2.setLocationRelativeTo(null);
        
        mediaPlayer.setCycleCount(MediaPlayer.INDEFINITE);
        mediaPlayer.play();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        tesFish2 = new Tubes.tesFish();
        jFrame2 = new javax.swing.JFrame();
        BackSave = new javax.swing.JButton();
        SaveScore = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        playScore = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        mainPanel = new javax.swing.JPanel();
        newGame = new javax.swing.JButton();
        highScore = new javax.swing.JButton();
        about = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        aboutPanel = new javax.swing.JPanel();
        labelAbout = new javax.swing.JLabel();
        aboutBack = new javax.swing.JButton();
        helpPanel = new javax.swing.JPanel();
        helpBack = new javax.swing.JButton();
        helpLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        highscoresPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        hsBack = new javax.swing.JButton();

        jFrame1.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout tesFish2Layout = new javax.swing.GroupLayout(tesFish2);
        tesFish2.setLayout(tesFish2Layout);
        tesFish2Layout.setHorizontalGroup(
            tesFish2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        tesFish2Layout.setVerticalGroup(
            tesFish2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(tesFish2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(tesFish2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFrame2.setBounds(new java.awt.Rectangle(0, 0, 400, 145));
        jFrame2.setMinimumSize(new java.awt.Dimension(400, 200));
        jFrame2.setPreferredSize(new java.awt.Dimension(400, 200));
        jFrame2.setResizable(false);
        jFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackSave.setText("Back");
        BackSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackSaveMouseClicked(evt);
            }
        });
        jFrame2.getContentPane().add(BackSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        SaveScore.setText("Save");
        SaveScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveScoreMouseClicked(evt);
            }
        });
        jFrame2.getContentPane().add(SaveScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("GAME OVER");
        jFrame2.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 11, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("SCORE :");
        jFrame2.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 42, -1, -1));

        playScore.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFrame2.getContentPane().add(playScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 42, 60, 15));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("NAME  :");
        jFrame2.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 66, -1, -1));

        pname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFrame2.getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 63, 71, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setOpaque(false);

        newGame.setText("New Game");
        newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });

        highScore.setText("Highscores");
        highScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                highScoreMouseClicked(evt);
            }
        });

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(about, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(highScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(helpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(newGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(highScore)
                .addGap(65, 65, 65)
                .addComponent(helpButton)
                .addGap(69, 69, 69)
                .addComponent(about)
                .addGap(71, 71, 71)
                .addComponent(exitButton)
                .addGap(71, 71, 71))
        );

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        aboutPanel.setOpaque(false);

        labelAbout.setBackground(new java.awt.Color(255, 255, 255));
        labelAbout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelAbout.setText("Dibuat oleh kelompok 15");
        labelAbout.setOpaque(true);

        aboutBack.setText("Back");
        aboutBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(aboutBack))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(labelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(labelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(aboutBack)
                .addGap(45, 45, 45))
        );

        getContentPane().add(aboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        helpPanel.setOpaque(false);

        helpBack.setText("Back");
        helpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBackActionPerformed(evt);
            }
        });

        helpLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        helpLabel.setText("Gerakkan mouse untuk menggerakkan ikan");
        helpLabel.setOpaque(true);

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addGroup(helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helpPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(helpBack))
                    .addGroup(helpPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(helpBack)
                .addGap(61, 61, 61))
        );

        getContentPane().add(helpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tubes/bg4.jpg"))); // NOI18N
        background.setAlignmentY(0.0F);
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        highscoresPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        hsBack.setText("Back");
        hsBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hsBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout highscoresPanelLayout = new javax.swing.GroupLayout(highscoresPanel);
        highscoresPanel.setLayout(highscoresPanelLayout);
        highscoresPanelLayout.setHorizontalGroup(
            highscoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(highscoresPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(highscoresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hsBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        highscoresPanelLayout.setVerticalGroup(
            highscoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(highscoresPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(hsBack)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(highscoresPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        //main: about button
        aboutPanel.setVisible(true);
        mainPanel.setVisible(false);
    }//GEN-LAST:event_aboutActionPerformed

    private void aboutBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBackActionPerformed
        // TODO add your handling code here:
        //about: Back button
        mainPanel.setVisible(true);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_aboutBackActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        //main: help button
        helpPanel.setVisible(true);
        mainPanel.setVisible(false);        
    }//GEN-LAST:event_helpButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        //main: exit button
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void helpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBackActionPerformed
        // TODO add your handling code here:
        //help: Back button
        mainPanel.setVisible(true);
        helpPanel.setVisible(false);
    }//GEN-LAST:event_helpBackActionPerformed

    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed
        // TODO add your handling code here:
        //main: new game
        //background.setVisible(false);
        //tesFish1.setVisible(true);
        //mainPanel.setVisible(false);
        //background.setVisible(false);
        //tesFish1.setCursor(Cursor.getDefaultCursor());
        BufferedImage cursorImg = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice()
                .getDefaultConfiguration().createCompatibleImage(16, 16, Transparency.TRANSLUCENT);
        Cursor blankCursor = Toolkit.getDefaultToolkit().createCustomCursor(cursorImg, new Point(0, 0), "blank cursor");
        // Set the blank cursor to the JFrame.
        jFrame1.setCursor(blankCursor);  
        setVisible(false);
        jFrame1.setVisible(true);
        background.setVisible(false);
        thread.start();
        
        //tesFish1.thread.start();
        //tesFish1.setVisible(false);
        //mainPanel.setVisible(true);
    }//GEN-LAST:event_newGameActionPerformed

    private void highScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highScoreMouseClicked
        // TODO add your handling code here:
        //menu:highscore
        background.setVisible(false);
        model = (DefaultTableModel) table.getModel();
        mainPanel.setVisible(false);
        highscoresPanel.setVisible(true);
        rs = Database.show();
        if(rs != null){
            try {
                while(rs.next()){
                    model.addRow(new Object[]{rs.getString("username") , rs.getInt("score")});
                }
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_highScoreMouseClicked

    private void hsBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hsBackMouseClicked
        // TODO add your handling code here:
        //hs : back
        if(model.getRowCount()>0){
            for (int i = model.getRowCount() - 1; i > -1; i--) {
            model.removeRow(i);
            }            
        }
        highscoresPanel.setVisible(false);
        mainPanel.setVisible(true);
        background.setVisible(true);
    }//GEN-LAST:event_hsBackMouseClicked

    private void BackSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackSaveMouseClicked
        // TODO add your handling code here:
        //score : back
        jFrame2.setVisible(false);
        setVisible(true);
        mainPanel.setVisible(true);
        background.setVisible(true);        
        
    }//GEN-LAST:event_BackSaveMouseClicked

    private void SaveScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveScoreMouseClicked
        // TODO add your handling code here:
        //score : save
        score = Integer.parseInt(playScore.getText());
        nama =  pname.getText();
        Database.insert(nama, score); 
        pname.setText("");
        jFrame2.setVisible(false);
        setVisible(true);
        mainPanel.setVisible(true);   
        background.setVisible(true);        
    }//GEN-LAST:event_SaveScoreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    @Override
    public void run(){
        tesFish2.thread.start();
        while(tesFish2.thread.isAlive()){}
        jFrame1.setVisible(false);
        //setVisible(true);
        setPlayScore();
        tesFish2.newThread();
        thread = new Thread(this);
        //background.setVisible(true);
        mainPanel.setVisible(false);
        //saveScore.setVisible(true);
        jFrame2.setVisible(true);
    }
    
    void setPlayScore(){
        //scoreLabel.setText(""+tesFish2.gameScore);
        playScore.setText(""+tesFish2.gameScore);
        //System.out.println("tesFish2.gameScore: "+ tesFish2.gameScore);
    }
    
    Thread thread = new Thread(this);
    int score;
    String nama;
    ResultSet rs;
    static DefaultTableModel model;
    final URL resource = getClass().getResource("bgm.mp3");
    final JFXPanel fxPanel = new JFXPanel();
    Media hit = new Media(resource.toString());
    MediaPlayer mediaPlayer = new MediaPlayer(hit);    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackSave;
    private javax.swing.JButton SaveScore;
    private javax.swing.JButton about;
    private javax.swing.JButton aboutBack;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel background;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton helpBack;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JButton highScore;
    private javax.swing.JPanel highscoresPanel;
    private javax.swing.JButton hsBack;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAbout;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newGame;
    private javax.swing.JLabel playScore;
    private javax.swing.JTextField pname;
    private javax.swing.JTable table;
    private Tubes.tesFish tesFish2;
    // End of variables declaration//GEN-END:variables
}
